Ogbete
cyber-coders-j2017a/modern.core.java.repo pull request #57
Opened 2017-07-15 21:54 UTC by tccanini

2017-07-16 18:59 UTC, edwinchukus requested changes
Kindly make changes as requested.

2017-07-16 18:59 UTC, edwinchukus commented on Zoo/src/JosPlateau/Animals.java
> +            for (int i = 0; i < animalNames.length; i++) {
Hi Tim, I am not sure what this code is doing. This code would assign "String Number 1", etc. Kindly review it and reassign it.

2017-07-16 21:50 UTC, tccanini reviewed
reviewed as advised

2017-07-19 07:53 UTC, edwinchukus requested changes

2017-07-19 07:53 UTC, edwinchukus commented on Zoo/src/JosPlateau/AnimalsRunner.java
> +        System.out.println(yourList);
You cannot print isnatnce variable on the console. I need to see your thought process in these codes. I could explain more if need be.

2017-07-19 07:53 UTC, edwinchukus commented on Zoo/src/JosPlateau/AnimalsRunner2.java
> +        return;
main method does not need a return statement. Kindly review all our examples please.

2017-07-19 07:55 UTC, edwinchukus commented
I really need you to review all our examples right from day one before making these needed changes.

2017-07-19 18:16 UTC, tccanini commented
NG,

Kindly re review updated corrections on the above code . Please refer to Edwin's comments on each line that required amendment.

ta

2017-07-19 20:02 UTC, edwinchukus requested changes

2017-07-19 20:02 UTC, edwinchukus commented on Kaduna_Tim_Arrays/src/Control701/Main.java
> +        System.out.println();
I need you to remove this sout code.

2017-07-19 20:02 UTC, edwinchukus commented on Zoo/src/JosPlateau/Main.java
> +package JosPlateau;
Remove this piece of code!!!

2017-07-19 20:05 UTC, edwinchukus approved these changes

2017-07-19 20:06 UTC, merged