Wentworth
cyber-coders-j2017a/modern.core.java.repo pull request #75
Opened 2017-07-27 21:32 UTC by tccanini

2017-07-28 08:42 UTC, edwinchukus requested changes

2017-07-28 08:42 UTC, edwinchukus commented on Zoo/src/filesInJava/Geography.java
> +        String filePath = "/home/admin-batch-a/Desktop/TestDevelopment/Projects/modern.core.java.repo/Zoo";
This code will give error. There is no file name of it. Kindly double-check mine, it has like "other_folders/employee.txt" which is missing in your case.

2017-07-28 08:42 UTC, edwinchukus commented on Zoo/src/filesInJava/Geography.java
> +        String filePath = ("/home/admin-batch-a/Desktop/TestDevelopment/Projects/modern.core.java.repo/Zoo");
This code will give error. There is no file name of it. Kindly double-check mine, it has like "other_folders/employee.txt" which is missing in your case.

2017-07-29 11:24 UTC, tccanini commented on Zoo/src/filesInJava/Geography.java
> +        String filePath = "/home/admin-batch-a/Desktop/TestDevelopment/Projects/modern.core.java.repo/Zoo";
i have added a .txt file within the filepath line on the existing code

2017-07-29 11:25 UTC, tccanini commented on Zoo/src/filesInJava/Geography.java
> +        String filePath = ("/home/admin-batch-a/Desktop/TestDevelopment/Projects/modern.core.java.repo/Zoo");
All amended and seemed ok now..
please could review and approve.

thank you

2017-07-29 11:53 UTC, edwinchukus approved these changes
Excellent!!!

2017-07-29 11:53 UTC, merged